id = "rumdl"
name = "rumdl"
description = "Fast Markdown linter and formatter written in Rust"
version = "0.0.2"
schema_version = 1
authors = ["Ruben Jongejan <ruben.jongejan@gmail.com>"]
repository = "https://github.com/rvben/zed-rumdl"

[language_servers.rumdl]
name = "rumdl"
languages = ["Markdown"]
